#!/bin/dash

# This is my implementation of adding an <assignment>
# with provided <solution> <autotests> <automarking>
# into the .give directory

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different give scripts
. helpers.sh

# check invalid number of arguments
if [ "$#" -ne 4 ]
then
    echo "usage: give-add <assignment> <solution> <autotests> <automarking>" >&2
    exit 1
fi

assignment="$1"
solution="$2"
autotests="$3"
automarking="$4"

# check invalid assignment name
if ! echo "$assignment" | grep -E '^[a-z]+[a-zA-Z0-9_]*$' >/dev/null; then
    echo "give-add: invalid assignment: $assignment" >&2
    exit 1
fi

# check invalid solution name
if ! echo "$solution" | grep -E '^[a-zA-Z0-9_./-]+$' >/dev/null; then
    echo "give-add: invalid solution: $solution" >&2
    exit 1
fi

# create .give
if ! [ -d ".give" ]; then
    mkdir ".give"
    echo "directory .give created"
fi

# check <assignment> already exists
if [ -d ".give/$assignment" ]; then
    echo "give-add: assignment $assignment already exists" >&2
    exit 1
fi

# error check the passed in arguments
valid_file_check "$solution" "give-add"
valid_file_check "$autotests" "give-add"
valid_file_check "$automarking" "give-add"

# check the validity of the <autotests> content
edit_autotests="$(mktemp)"
sed 's/\\/\\\\/g' "$autotests" > "$edit_autotests"
autotests_error_checks "$autotests" "$edit_autotests"
rm -f "$edit_autotests"

# check the validity of the <automarking> content
edit_automarking="$(mktemp)"
sed 's/\\/\\\\/g' "$automarking" > "$edit_automarking"
automarking_error_checks "$automarking" "$edit_automarking"
rm -f "$edit_automarking"

### create a valid give-add
mkdir ".give/$assignment"
mkdir ".give/$assignment/_SOLUTION"
cp "$solution" ".give/$assignment/_SOLUTION"
cp "$autotests" ".give/$assignment/_AUTOTESTS"
cp "$automarking" ".give/$assignment/_AUTOMARKING"

echo "assignment $assignment created"