#!/bin/dash

# This is my implementation of adding an <assignment>
# with provided <solution> <autotests> <automarking>
# into the .give directory

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different give scripts
. helpers.sh

give_not_exist "give-summary"

# loop through the assignments
# use find with mindepth maxdepth to count unique student dirs
for assignment in .give/*; do
    # all assignments should be directories
    # so if we encounter a non-directory then
    # this means that these is no assignment
    if ! [ -d "$assignment" ]
    then
        echo "no assignments"
        exit 0
    fi
    assignment_name="$(echo "$assignment" | cut -d '/' -f2,2)"
    num_students="$(find "$assignment" -mindepth 1 -maxdepth 1 -type d | 
        cut -d '/' -f3,3 | 
        grep -Ec 'z[0-9]{7}')"

    echo "assignment $assignment_name: submissions from $num_students students"  
done