#!/bin/dash

# A student who is identified by their <zid>
# can submit their <solution> to the <assignment>
# via give-submit.

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different give scripts
. helpers.sh

# from helpers.sh
# checks if .give does not exist
give_not_exist "give-submit"

# check invalid number of arguments
if [ $# -ne 3 ]; then
    echo "usage: give-submit <assignment> <zid> <filename>" >&2
    exit 1
fi

assignment="$1"
zid="$2"
filename="$3"

# check invalid assignment
if ! echo "$assignment" | grep -E '^[a-z]+[a-zA-Z0-9_]*$' >/dev/null; then
    echo "give-submit: invalid assignment: $assignment" >&2
    exit 1
fi

# check invalid zid
if ! echo "$zid" | grep -E '^z[0-9]{7}$' >/dev/null; then
    echo "give-submit: invalid zid: $zid" >&2
    exit 1
fi

# check invalid filename
if ! echo "$filename" | grep -E '^[a-zA-Z0-9_./-]+$' >/dev/null; then
    echo "give-submit: invalid filename: $filename" >&2
    exit 1
fi

# check if assignment can be found as a directory
if ! [ -d ".give/$assignment" ]; then
    echo "give-submit: assignment $assignment not found" >&2
    exit 1
fi

valid_file_check "$filename" "give-submit"

# create a valid give-submit
if ! [ -d ".give/$assignment/$zid" ]; then
    mkdir ".give/$assignment/$zid"
fi
# find the nth number of submission that will be created
submission_num="$(find ".give/$assignment/$zid" -type d | wc -l)" 
mkdir ".give/$assignment/$zid/$submission_num"
cp "$filename" ".give/$assignment/$zid/$submission_num"

# create timestamp
curr_time="$(date "+%c")"
# format it to the spec via sed
format_time="$(echo "$curr_time" |
sed -E 's/([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*)$/\1 \3 \2 \5 \4/' |
sed -E 's/([a-zA-Z]{3} [a-zA-Z]{3} )0([1-9])/\1 \2/')"

# insert formatted time into @TIMESTAMP
echo "$format_time" >".give/$assignment/$zid/$submission_num/@TIMESTAMP"
bytes="$(wc -c "$filename"|cut -d ' ' -f1,1)"
filename="$(echo "$filename" | rev | cut -d '/' -f1,1 | rev)"

# print out success
echo "Submission accepted - submission $submission_num: $filename $bytes bytes @ $format_time"