#!/bin/dash

# This will delete the targeted <assignment>

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different give scripts
. helpers.sh

give_not_exist "give-rm"

if [ $# -ne 1 ]; then
    echo "usage: give-rm <assignment>" >&2
    exit 1
fi

assignment="$1"

# check invalid assignment
if ! echo "$assignment" | grep -E '^[a-z]+[a-zA-Z0-9_]*$' >/dev/null; then
    echo "give-rm: invalid assignment: $assignment" >&2
    exit 1
fi

# check assignment exists
if ! [ -d ".give/$assignment" ]; then
    echo "give-rm: assignment $assignment not found" >&2
    exit 1
fi

rm -rf ".give/$assignment"
echo "assignment $assignment removed"