#!/bin/bash

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different quicktest scripts
. helpers.sh

# from helpers.sh
# checks if .quicktest does not exist
quicktest_not_exist "quicktest-submit"

# check invalid number of arguments
if [ $# -ne 3 ]; then
    echo "usage: quicktest-submit <project> <user> <filename>" >&2
    exit 1
fi

project="$1"
user="$2"
filename="$3"

# check invalid project
if ! echo "$project" | grep -E '^[a-z]+[a-zA-Z0-9_]*$' >/dev/null; then
    echo "quicktest-submit: invalid project: $project" >&2
    exit 1
fi

# check invalid user
if ! echo "$user" | grep -E "^[^_].*" >/dev/null; then
    echo "quicktest-submit: invalid user: $user" >&2
    exit 1
fi

# check invalid filename
if ! echo "$filename" | grep -E '^[a-zA-Z0-9_./-]+$' >/dev/null; then
    echo "quicktest-submit: invalid filename: $filename" >&2
    exit 1
fi

# check if project can be found as a directory
if ! [ -d ".quicktest/$project" ]; then
    echo "quicktest-submit: project $project not found" >&2
    exit 1
fi

valid_file_check "$filename" "quicktest-submit"

# create a valid quicktest-submit
if ! [ -d ".quicktest/$project/$user" ]; then
    mkdir ".quicktest/$project/$user"
fi
# find the nth number of submission that will be created
submission_num="$(find ".quicktest/$project/$user" -type d | wc -l)" 
mkdir ".quicktest/$project/$user/$submission_num"
cp "$filename" ".quicktest/$project/$user/$submission_num"

# create timestamp
curr_time="$(date "+%c")"
# format it to the spec via sed
format_time="$(echo "$curr_time" |
sed -E 's/([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*)$/\1 \3 \2 \5 \4/' |
sed -E 's/([a-zA-Z]{3} [a-zA-Z]{3} )0([1-9])/\1 \2/')"

# insert formatted time into @TIMESTAMP
echo "$format_time" >".quicktest/$project/$user/$submission_num/@TIMESTAMP"
bytes="$(wc -c "$filename"|cut -d ' ' -f1,1)"
filename="$(echo "$filename" | rev | cut -d '/' -f1,1 | rev)"

# print out success
echo "Submission accepted - submission $submission_num: $filename $bytes bytes @ $format_time"