#!/bin/bash

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different quicktest scripts
. helpers.sh

quicktest_not_exist "quicktest-rm"

if [ $# -ne 1 ]; then
    echo "usage: quicktest-rm <assignment>" >&2
    exit 1
fi

assignment="$1"

# check invalid assignment
if ! echo "$assignment" | grep -E '^[a-z]+[a-zA-Z0-9_]*$' >/dev/null; then
    echo "quicktest-rm: invalid assignment: $assignment" >&2
    exit 1
fi

# check assignment exists
if ! [ -d ".quicktest/$assignment" ]; then
    echo "quicktest-rm: assignment $assignment not found" >&2
    exit 1
fi

rm -rf ".quicktest/$assignment"
echo "assignment $assignment removed"