#!/bin/bash

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different quicktest scripts
. helpers.sh

quicktest_not_exist "quicktest-summary"

# loop through the assignments
# use find with mindepth maxdepth to count unique version dirs
for assignment in .quicktest/*; do
    # all assignments should be directories
    # so if we encounter a non-directory then
    # this means that these is no assignment
    if ! [ -d "$assignment" ]
    then
        echo "no assignments"
        exit 0
    fi
    assignment_name="$(echo "$assignment" | cut -d '/' -f2,2)"
    num_versions="$(find "$assignment" -mindepth 1 -maxdepth 1 -type d | 
        cut -d '/' -f3,3 | 
        grep -Ec 'z[0-9]{7}')"

    echo "assignment $assignment_name: submissions from $num_versions versions"  
done