#!/bin/bash

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different quicktest scripts
. helpers.sh

quicktest_not_exist "quicktest-fetch"

# number of args have to be 2 or 3
if [ $# -ne 2 ] && [ $# -ne 3 ]; then
    echo "usage: quicktest-fetch <assignment> <id> [n]" >&2
    exit 1
fi

assignment="$1"
id="$2"

# check invalid assignment
if ! echo "$assignment" | grep -E '^[a-z]+[a-zA-Z0-9_]*$' >/dev/null; then
    echo "quicktest-fetch: invalid assignment: $assignment" >&2
    exit 1
fi

# check invalid id
if ! echo "$id" | grep -E '^z[0-9]{7}$' >/dev/null; then
    echo "quicktest-fetch: invalid id: $id" >&2
    exit 1
fi

# check valid assignment directory
if ! [ -d ".quicktest/$assignment" ]; then
    echo "quicktest-fetch: assignment $assignment not found" >&2
    exit 1
fi

# if n is not positive then simply do total submission + negative n
# this would equal to nth submission if n was to be positive
# e.g. if n=0, then total_submission - 0 = (total_submission)th
# e.g. if n=-1, then total_submission + (-1) = (total_submission-1)th = 2nd last submission
# if n is positive then just use that nth submission
version="$(find ".quicktest/$assignment" -mindepth 1 -maxdepth 1 -type d | grep -E "$id")" 2>/dev/null
num_submissions="$(find "$version" -mindepth 1 -maxdepth 1 -type d | wc -l)" 2>/dev/null

n=0
if [ $# -eq 3 ]; then
    n="$3"
fi

if [ "$n" -gt "$num_submissions" ] || [ "$n" -le $((-num_submissions)) ]; then
    echo "quicktest-fetch: submission $n not found for $assignment" >&2
    exit 1
fi

if [ "$n" -le 0 ]; then
    n=$((n+num_submissions))
fi
get_submission="$(find "$version" -mindepth 1 -maxdepth 1 -type d|sort -n|head -"$n"|tail -1)" 2>/dev/null
file="$(find "$get_submission" -mindepth 1 -maxdepth 1|grep -Ev '@TIMESTAMP')" 2>/dev/null
cat "$file"