#!/bin/bash

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different quicktest scripts
. helpers.sh

quicktest_not_exist "quicktest-status"

# check num args 
if [ $# -ne 1 ]; then
    echo "usage: quicktest-status <user>" >&2
    exit 1
fi

user="$1"

# check invalid user
if ! echo "$user" | grep -E "^[^_].*" >/dev/null; then
    echo "quicktest-status: invalid user: $user" >&2
    exit 1
fi

user_match=0
for project in .quicktest/*; do
    # check no projects
    if ! [ -d "$project" ]; then
        echo "no submissions for $user"
        exit 0
    fi
    project_name="$(echo "$project" | cut -d '/' -f2,2)"
    user="$(find "$project" -mindepth 1 -maxdepth 1 -type d | grep -E "$user")" 2>/dev/null
    # if no user could be found then iterate to the next project
    if [ $? -eq 1 ]; then
        continue
    fi    
    user_match=1
    submissions="$(find "$user" -mindepth 1 -maxdepth 1 -type d | sort -n)" 2>/dev/null
    num_submissions="$(find "$user" -mindepth 1 -maxdepth 1 -type d | wc -l)" 2>/dev/null
    echo "* $num_submissions submissions for $project_name"

    for submission in $submissions; do
        # submission_num="$(echo "$submission"|rev|cut -d '/' -f1,1)"
        submission_num="$(echo "$submission" | cut -d '/' -f4,4)"

        # find the submitted file that is not TIMESTAMP
        file="$(find "$submission" -mindepth 1 -maxdepth 1|grep -Ev '@TIMESTAMP')" 2>/dev/null       
        filename="$(echo "$file" | cut -d '/' -f5,5)"
        file_size="$(wc -c "$file" | cut -d ' ' -f1,1)"

        # find the TIMESTAMP
        timestamp="$(find "$submission" -mindepth 1 -maxdepth 1|grep -E '@TIMESTAMP')" 2>/dev/null
        print_timestamp="$(cat "$timestamp")"
        echo "submission $submission_num: $filename $file_size bytes @ $print_timestamp"
    done
done

# no matching user for all projects
if [ "$user_match" -eq 0 ]; then
    echo "no submissions for $user"
fi
