#!/bin/bash

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different quicktest scripts
. helpers.sh

# check invalid number of arguments
if [ "$#" -ne 4 ]
then
    echo "usage: quicktest-add <project> <solution> <autotests> <automarking>" >&2
    exit 1
fi

project="$1"
solution="$2"
autotests="$3"
automarking="$4"

# check invalid project name
if ! echo "$project" | grep -E '^[a-z]+[a-zA-Z0-9_]*$' >/dev/null; then
    echo "quicktest-add: invalid project: $project" >&2
    exit 1
fi

# check invalid solution name
if ! echo "$solution" | grep -E '^[a-zA-Z0-9_./-]+$' >/dev/null; then
    echo "quicktest-add: invalid solution: $solution" >&2
    exit 1
fi

# create .quicktest
if ! [ -d ".quicktest" ]; then
    mkdir ".quicktest"
    echo "directory .quicktest created"
fi

# check <project> already exists
if [ -d ".quicktest/$project" ]; then
    echo "quicktest-add: project $project already exists" >&2
    exit 1
fi

# error check the passed in arguments
valid_file_check "$solution" "quicktest-add"
valid_file_check "$autotests" "quicktest-add"
valid_file_check "$automarking" "quicktest-add"

# check the validity of the <autotests> content
edit_autotests="$(mktemp)"
sed 's/\\/\\\\/g' "$autotests" > "$edit_autotests"
autotests_error_checks "$autotests" "$edit_autotests"
rm -f "$edit_autotests"

# check the validity of the <automarking> content
edit_automarking="$(mktemp)"
sed 's/\\/\\\\/g' "$automarking" > "$edit_automarking"
automarking_error_checks "$automarking" "$edit_automarking"
rm -f "$edit_automarking"

### create a valid quicktest-add
mkdir ".quicktest/$project"
mkdir ".quicktest/$project/_SOLUTION"
cp "$solution" ".quicktest/$project/_SOLUTION"
cp "$autotests" ".quicktest/$project/_AUTOTESTS"
cp "$automarking" ".quicktest/$project/_AUTOMARKING"

echo "project $project created"