#!/bin/bash

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different quicktest scripts
. helpers.sh

# from helpers.sh
# checks if .quicktest does not exist
quicktest_not_exist "quicktest-submit"

# check invalid number of arguments
if [ $# -ne 3 ]; then
    echo "usage: quicktest-submit <assignment> <id> <filename>" >&2
    exit 1
fi

assignment="$1"
id="$2"
filename="$3"

# check invalid assignment
if ! echo "$assignment" | grep -E '^[a-z]+[a-zA-Z0-9_]*$' >/dev/null; then
    echo "quicktest-submit: invalid assignment: $assignment" >&2
    exit 1
fi

# check invalid id
if ! echo "$id" | grep -E '^z[0-9]{7}$' >/dev/null; then
    echo "quicktest-submit: invalid id: $id" >&2
    exit 1
fi

# check invalid filename
if ! echo "$filename" | grep -E '^[a-zA-Z0-9_./-]+$' >/dev/null; then
    echo "quicktest-submit: invalid filename: $filename" >&2
    exit 1
fi

# check if assignment can be found as a directory
if ! [ -d ".quicktest/$assignment" ]; then
    echo "quicktest-submit: assignment $assignment not found" >&2
    exit 1
fi

valid_file_check "$filename" "quicktest-submit"

# create a valid quicktest-submit
if ! [ -d ".quicktest/$assignment/$id" ]; then
    mkdir ".quicktest/$assignment/$id"
fi
# find the nth number of submission that will be created
submission_num="$(find ".quicktest/$assignment/$id" -type d | wc -l)" 
mkdir ".quicktest/$assignment/$id/$submission_num"
cp "$filename" ".quicktest/$assignment/$id/$submission_num"

# create timestamp
curr_time="$(date "+%c")"
# format it to the spec via sed
format_time="$(echo "$curr_time" |
sed -E 's/([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*) ([^ ]*)$/\1 \3 \2 \5 \4/' |
sed -E 's/([a-zA-Z]{3} [a-zA-Z]{3} )0([1-9])/\1 \2/')"

# insert formatted time into @TIMESTAMP
echo "$format_time" >".quicktest/$assignment/$id/$submission_num/@TIMESTAMP"
bytes="$(wc -c "$filename"|cut -d ' ' -f1,1)"
filename="$(echo "$filename" | rev | cut -d '/' -f1,1 | rev)"

# print out success
echo "Submission accepted - submission $submission_num: $filename $bytes bytes @ $format_time"