#!/bin/bash

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different quicktest scripts
. helpers.sh

quicktest_not_exist "quicktest-summary"

# loop through the projects
# use find with mindepth maxdepth to count unique user dirs
for project in .quicktest/*; do
    # all projects should be directories
    # so if we encounter a non-directory then
    # this means that these is no project
    if ! [ -d "$project" ]
    then
        echo "no projects"
        exit 0
    fi
    project_name="$(echo "$project" | cut -d '/' -f2,2)"
    num_users="$(find "$project" -mindepth 1 -maxdepth 1 -type d | 
        cut -d '/' -f3,3 | 
        grep -Ec "^[^_].*")"

    echo "project $project_name: submissions from $num_users users"  
done