#!/bin/bash

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different quicktest scripts
. helpers.sh

quicktest_not_exist "quicktest-rm"

if [ $# -ne 1 ]; then
    echo "usage: quicktest-rm <project>" >&2
    exit 1
fi

project="$1"

# check invalid project
if ! echo "$project" | grep -E '^[a-z]+[a-zA-Z0-9_]*$' >/dev/null; then
    echo "quicktest-rm: invalid project: $project" >&2
    exit 1
fi

# check project exists
if ! [ -d ".quicktest/$project" ]; then
    echo "quicktest-rm: project $project not found" >&2
    exit 1
fi

rm -rf ".quicktest/$project"
echo "project $project removed"