#!/bin/bash

PATH="$PATH:$(pwd)"

# NOTE: this file contains all helper functions
# which are used across different quicktest scripts
. helpers.sh

quicktest_not_exist "quicktest-status"

# check num args 
if [ $# -ne 1 ]; then
    echo "usage: quicktest-status <id>" >&2
    exit 1
fi

id="$1"

# check invalid id
if ! echo "$id" | grep -E '^z[0-9]{7}$' >/dev/null; then
    echo "quicktest-status: invalid id: $id" >&2
    exit 1
fi

id_match=0
for assignment in .quicktest/*; do
    # check no assignments
    if ! [ -d "$assignment" ]; then
        echo "no submissions for $id"
        exit 0
    fi
    assignment_name="$(echo "$assignment" | cut -d '/' -f2,2)"
    version="$(find "$assignment" -mindepth 1 -maxdepth 1 -type d | grep -E "$id")" 2>/dev/null
    # if no version could be found then iterate to the next assignment
    if [ $? -eq 1 ]; then
        continue
    fi    
    id_match=1
    submissions="$(find "$version" -mindepth 1 -maxdepth 1 -type d | sort -n)" 2>/dev/null
    num_submissions="$(find "$version" -mindepth 1 -maxdepth 1 -type d | wc -l)" 2>/dev/null
    echo "* $num_submissions submissions for $assignment_name"

    for submission in $submissions; do
        # submission_num="$(echo "$submission"|rev|cut -d '/' -f1,1)"
        submission_num="$(echo "$submission" | cut -d '/' -f4,4)"

        # find the submitted file that is not TIMESTAMP
        file="$(find "$submission" -mindepth 1 -maxdepth 1|grep -Ev '@TIMESTAMP')" 2>/dev/null       
        filename="$(echo "$file" | cut -d '/' -f5,5)"
        file_size="$(wc -c "$file" | cut -d ' ' -f1,1)"

        # find the TIMESTAMP
        timestamp="$(find "$submission" -mindepth 1 -maxdepth 1|grep -E '@TIMESTAMP')" 2>/dev/null
        print_timestamp="$(cat "$timestamp")"
        echo "submission $submission_num: $filename $file_size bytes @ $print_timestamp"
    done
done

# no matching id for all assignments
if [ "$id_match" -eq 0 ]; then
    echo "no submissions for $id"
fi
